### ISSUE TITLE
"failed to download" for all assets scripts

### ISSUE THREAD

**Issue by mjc87** [NASA-IMPACT/csdap-bulk-download#26]
I'm unable to get any download scripts to work. I can download individual files one at a time just fine in the CSDA web GUI, but when I attempt to use this software with any assets.csv file that I download using the 'Download Inventory' button, I get a "Failed to download" message for every file (I have tried multiple file types...). I have ruled out an authentication issue, as I tried entering incorrect ones and that gives an authentication error instead of the error I am seeing.

If it matters, I installed using pip install as suggested.

Example:

```
~/.local/bin/csdap-bulk-download assets.csv
Earthdata Login username: ******
Earthdata Login password: 
2022-03-08 17:46:53,431:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antPOD.rnx: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104.sp3: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antFRO.rnx: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120.sp3: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-47-20_FM120_navigation/spire_att_L1A_leoAtt_v06.01_2021-01-18T00-00-00_FM120.log: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antFRO.rnx: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1B_leoOrb_v06.01_2021-01-17T23-00-24_FM104.sp3: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antBRO.rnx: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1B_leoOrb_v06.01_2021-01-17T23-47-20_FM120.sp3: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-00-24_FM104_navigation/spire_att_L1A_leoAtt_v06.01_2021-01-17T23-00-00_FM104.log: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antPOD.rnx: Failed to download
2022-03-08 17:46:53,439:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antBRO.rnx: Failed to download
Complete.
```

assets.csv:

```
collection_id,scene_id,asset_type
"spire","2021-01-17T23-47-20_FM120_navigation","spire_att_L1A_leoAtt_v06.01_2021-01-18T00-00-00_FM120.log"
"spire","2021-01-17T23-47-20_FM120_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120.sp3"
"spire","2021-01-17T23-47-20_FM120_navigation","spire_nav_L1B_leoOrb_v06.01_2021-01-17T23-47-20_FM120.sp3"
"spire","2021-01-17T23-47-20_FM120_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antBRO.rnx"
"spire","2021-01-17T23-47-20_FM120_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antFRO.rnx"
"spire","2021-01-17T23-47-20_FM120_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antPOD.rnx"
"spire","2021-01-17T23-00-24_FM104_navigation","spire_att_L1A_leoAtt_v06.01_2021-01-17T23-00-00_FM104.log"
"spire","2021-01-17T23-00-24_FM104_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104.sp3"
"spire","2021-01-17T23-00-24_FM104_navigation","spire_nav_L1B_leoOrb_v06.01_2021-01-17T23-00-24_FM104.sp3"
"spire","2021-01-17T23-00-24_FM104_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antBRO.rnx"
"spire","2021-01-17T23-00-24_FM104_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antFRO.rnx"
"spire","2021-01-17T23-00-24_FM104_navigation","spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antPOD.rnx"
```

Any suggestions for how to troubleshoot?

**Comment by alukach** [comment]
@mjc87 Can you please share the output of the same command if you append `-v` for increased verbosity?

**Comment by mjc87** [comment]
@alukach Sure thing... It's only a bit different.

```
2022-03-08 18:20:42,599:Authenticating with Earthdata Login...
2022-03-08 18:20:42,814:Exchanging authorization code for access token...
2022-03-08 18:20:44,033:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antFRO.rnx: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104.sp3: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antPOD.rnx: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antBRO.rnx: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1B_leoOrb_v06.01_2021-01-17T23-00-24_FM104.sp3: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120_antBRO.rnx: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1B_leoOrb_v06.01_2021-01-17T23-47-20_FM120.sp3: Failed to download
2022-03-08 18:20:44,046:spire/2021-01-17T23-47-20_FM120_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-47-20_FM120.sp3: Failed to download
2022-03-08 18:20:44,047:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antPOD.rnx: Failed to download
2022-03-08 18:20:44,047:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antFRO.rnx: Failed to download
2022-03-08 18:20:44,047:spire/2021-01-17T23-00-24_FM104_navigation/spire_att_L1A_leoAtt_v06.01_2021-01-17T23-00-00_FM104.log: Failed to download
2022-03-08 18:20:44,047:spire/2021-01-17T23-47-20_FM120_navigation/spire_att_L1A_leoAtt_v06.01_2021-01-18T00-00-00_FM120.log: Failed to download
Complete.
```

**Comment by mjc87** [comment]
With `-vv` I get the following:

```
2022-03-08 18:22:03,551:urllib3.connectionpool:MainThread:DEBUG:Starting new HTTPS connection (1): csdap.earthdata.nasa.gov:443
2022-03-08 18:22:03,899:urllib3.connectionpool:MainThread:DEBUG:https://csdap.earthdata.nasa.gov:443 "GET /api/v1/auth/?redirect_uri=script HTTP/1.1" 307 None
2022-03-08 18:22:03,905:csdap_bulk_download.csdap:MainThread:DEBUG:Authenticating with Earthdata Login...
2022-03-08 18:22:03,907:urllib3.connectionpool:MainThread:DEBUG:Starting new HTTPS connection (1): urs.earthdata.nasa.gov:443
2022-03-08 18:22:04,077:urllib3.connectionpool:MainThread:DEBUG:https://urs.earthdata.nasa.gov:443 "GET /oauth/authorize?client_id=N99GqJO2jik_BOKRqUMeUA&redirect_uri=https%3A%2F%2Fcsdap.earthdata.nasa.gov%2Fapi%2Fv1%2Fauth%2Fcomplete&response_type=code&state=script HTTP/1.1" 302 None
2022-03-08 18:22:04,082:csdap_bulk_download.csdap:MainThread:DEBUG:Exchanging authorization code for access token...
2022-03-08 18:22:04,083:urllib3.connectionpool:MainThread:DEBUG:Starting new HTTPS connection (1): csdap.earthdata.nasa.gov:443
2022-03-08 18:22:05,227:urllib3.connectionpool:MainThread:DEBUG:https://csdap.earthdata.nasa.gov:443 "POST /api/v1/auth/token HTTP/1.1" 200 None
2022-03-08 18:22:05,233:csdap_bulk_download.cli:MainThread:ERROR:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antPOD.rnx generated an exception: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>
Traceback (most recent call last):
  File "/Users/<username>/.local/lib/python3.7/site-packages/csdap_bulk_download/cli.py", line 151, in cli
    logger.info("%s: %s", path, future.result())
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/<username>/.local/lib/python3.7/site-packages/csdap_bulk_download/csdap.py", line 111, in download_file
    file_dir = out_dir / path
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/pathlib.py", line 928, in __rtruediv__
    return self._from_parts([key] + self._parts)
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/pathlib.py", line 666, in _parse_args
    % type(a))
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>
2022-03-08 18:22:05,245:csdap_bulk_download.cli:MainThread:ERROR:spire/2021-01-17T23-00-24_FM104_navigation/spire_nav_L1A_podObs_v06.01_2021-01-17T23-00-24_FM104_antFRO.rnx generated an exception: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>
Traceback (most recent call last):
  File "/Users/mjcrotea/.local/lib/python3.7/site-packages/csdap_bulk_download/cli.py", line 151, in cli
    logger.info("%s: %s", path, future.result())
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/<username>/.local/lib/python3.7/site-packages/csdap_bulk_download/csdap.py", line 111, in download_file
    file_dir = out_dir / path
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/pathlib.py", line 928, in __rtruediv__
    return self._from_parts([key] + self._parts)
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/<username>/miniconda3/envs/research37/lib/python3.7/pathlib.py", line 666, in _parse_args
    % type(a))
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>

...

Complete.
```

On Python 3.7 via anaconda, fwiw

**Comment by alukach** [comment]
@mjc87 I'm unable to reproduce.  Can you please reinstall the tool again and verify that there's still an issue?

```
pip install --upgrade --force-reinstall https://github.com/NASA-IMPACT/csdap-bulk-download/archive/main.zip
```

**Comment by mjc87** [comment]
@alukach I created a clean conda environment and cleaned up some things in my shell, and now things seem to be working. Not sure what the issue really was, but it does not appear to have been with this software so I will close this issue. Thanks for the help!
